### ISSUE TITLE
perf-test: broken text color from light mode

### ISSUE THREAD

**Issue by tinyjin** [thorvg/thorvg.web#26]
![CleanShot 2024-06-10 at 18 27 55](https://github.com/thorvg/thorvg.web/assets/11167117/0f5a3dca-f0de-462f-bacf-ade815836046)

The text "player" should be always white color.

**Comment by hermet** [comment]
Confirmed:
![image](https://github.com/thorvg/thorvg.web/assets/3711518/94cc0451-355d-401c-b79c-ccfefe03e4b7)
