### ISSUE TITLE
Support Render Config Option

### ISSUE THREAD

**Issue by tinyjin** [thorvg/thorvg.web#32]
Rendering configs for users to enable advanced mode. Provides users with control over rendering features.

```ts
interface RenderConfig {
  devicePixelRatio?: number; // default: 1.0
  viewportEnabled?: boolean; // default: true
  renderVisibleOnly?: boolean; // default: true  
}
```

**Comment by hermet** [comment]
@tinyjin I think these two are not user-considerable options. Please consider if they are really necessary for our player.
```
  viewportEnabled?: boolean; // default: true
  renderVisibleOnly?: boolean; // default: true  
```

**Comment by tinyjin** [comment]
> @tinyjin I think these two are not user-considerable options. Please consider if they are really necessary for our player.
> 
> ```
>   viewportEnabled?: boolean; // default: true
>   renderVisibleOnly?: boolean; // default: true  
> ```

Was thinking it'd be good if user can choose, because it doesn't harm current default options. But I think It's not so necessary!

We can now go with just single option.
```ts
interface RenderConfig {
  devicePixelRatio?: number; // default: 1.0
}
```

**Comment by tinyjin** [comment]
Since renderConfig will have only option, I'll include this support in #31 31
