### ISSUE TITLE
Perf-Test: Performance (fps) is dropped until scrolling

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg.web#5]
FPS shows lower results until the entire screen is scrolled. It seems to account for players outside the viewport. This needs to be rectified.

**Comment by theashraf** [comment]
I think it's because in dotlottie-react there is no check if the canvas is initially outside of the viewport or not before starting observing it

**Comment by tinyjin** [comment]
I think it should be applied in each player side. Do you think perf-test should tweak something to do this?

**Comment by theashraf** [comment]
@tinyjin Agreed, i've updated dotlottie-react with this patch, it's much better now
