### ISSUE TITLE
ensure consistent animations test set for performance assessment

### ISSUE THREAD

**Issue by theashraf** [thorvg/thorvg.web#7]
For better performance assessment, I think we should avoid randomizing the animations test set we use. We should ensure it is consistent across all players because, as far as I understand, not all animations have the same features, which might impact performance

**Comment by hermet** [comment]
The test tool allows users to use a random seed to reproduce the same contents set. they can copy & paste it, if they'd like to compare them.
![image](https://github.com/thorvg/thorvg.web/assets/3711518/99df2c68-677f-40c6-a331-452d0a1fce33)

**Comment by tinyjin** [comment]
We can keep same test set with the queryparameter `seed`. Thanks, I'm closing this issue :)
